develop -> master
shrlok/DevOps-experience pull request #4
Opened 2022-09-17 19:54 UTC by shrlok

create Dockrerfile
create an easy web server on python
add index.html

2022-09-17 20:01 UTC, ctrlok commented on web_server/Dockerfile
> +RUN mkdir /usr/bin/web_server
зачем использовать две отдельные команды mkdir, а не && символ что б выполнить последоватьльно? Посмотри ещё на `-p` у команды mkdir

2022-09-17 20:07 UTC, ctrlok requested changes

2022-09-17 20:07 UTC, ctrlok commented on web_server/Dockerfile
> +COPY ./python_web_server/main.py /usr/bin/web_server/
может проще будет сразу все файлы копировать?

2022-09-17 20:07 UTC, ctrlok commented on web_server/Dockerfile
> +CMD python3 /usr/bin/web_server/main.py
это в продакшен режиме запускается? Есть ли у этого сервера продакшен и дебаг режимы?

2022-09-17 20:07 UTC, ctrlok commented on web_server/Dockerfile
> +CMD python3 /usr/bin/web_server/main.py
добавь ещё [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose) и [HEALTHCECK](https://docs.docker.com/engine/reference/builder/#healthcheck)

2022-09-17 20:31 UTC, shrlok commented on web_server/Dockerfile
> +CMD python3 /usr/bin/web_server/main.py
> это в продакшен режиме запускается? Есть ли у этого сервера продакшен и дебаг режимы?
Нету, разработчики библиотеки socket вообще не рекомендуют его использовать в продакшн, из-за не секьюрности.

2022-09-22 12:22 UTC, ctrlok approved these changes

2022-09-22 12:25 UTC, ctrlok commented on web_server/python_web_server/main.py
> +        server.bind(("127.0.0.1", 8080))
не слушай локалхост внутри контейнера

2022-09-23 19:24 UTC, shrlok commented on web_server/python_web_server/main.py
> +        server.bind(("127.0.0.1", 8080))
это старый комит был, проблема оказалась в том что я не пересобрал имадж

2022-09-24 18:21 UTC, merged